export const NODE_DEFAULT_COLOR = "#AAA";
export const EDGE_DEFAULT_COLOR = NODE_DEFAULT_COLOR;

export const NODE_INFLUENCED_COLOR = "#46C800";
export const EDGE_INFLUENCED_COLOR = NODE_INFLUENCED_COLOR;

export const NODE_INFLUENCING_COLOR = "#dc9600";
export const EDGE_INFLUENCING_COLOR = NODE_INFLUENCING_COLOR;

export const NODE_NOT_INFLUENCED_COLOR = "#FF4444";
export const EDGE_NOT_INFLUENCED_COLOR = NODE_NOT_INFLUENCED_COLOR;
